### ISSUE TITLE
Question: RethinkDB Changefeeds

### ISSUE THREAD

**Issue by niallobrien** [js-data/js-data-rethinkdb#18]
Hi, I'm just wondering how we can utilise RethinkDB's changefeeds with js-data? Thanks in advance.

**Comment by jmdobry** [comment]
After you create an adapter the underlying rethinkdbdash object is accessible at `adapter.r`. Using that you can make your changefeed. In your browser, connect to the change feed, and in the changefeed's callback you can respond to the changes appropriately, ie. inject new or updated data into the store, eject deleted data from the store, etc.

------

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of rethinkdb, js-data-rethinkdb, js-data, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is handled via the [Slack Channel](https://slack.js-data.io) (there's a channel for js-data-rethinkdb) or the [Mailing list](https://groups.io/org/groupsio/jsdata).
